[package]
name = "xvideo_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.27.5"
pollster = "0.2"
xvideo_engine = { path = "../xvideo_engine" }
